<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Braintree\Block\Paypal\Button;

/** @var Button $block */
try {
    $paypalId = sprintf('paypal-%s-%d', $block->getContainerId(), random_int(PHP_INT_MIN, PHP_INT_MAX));
    $paypalCreditId = sprintf('paypalcredit-%s-%d', $block->getContainerId(), random_int(PHP_INT_MIN, PHP_INT_MAX));
} catch (Exception $e) {
    /**
     * Exception only thrown if an appropriate source of randomness cannot be found.
     * https://www.php.net/manual/en/function.random-int.php
     */
    $paypalId = sprintf('paypal-%s', $block->getContainerId());
    $paypalCreditId = sprintf('paypalcredit-%s', $block->getContainerId());
}

$config = [
    'Gene_BraintreeHiConversion/js/paypal/button-cart' => [
        'config' => [
            'actionSuccess' => $block->getActionSuccess(),
            'clientToken' => $block->getClientToken(),
            'color' => $block->getButtonColor(),
            'disabledFunding' => $block->getDisabledFunding(),
            'displayName' => $block->getMerchantName(),
            'environment' => $block->getEnvironment(),
            'fundingicons' => $block->getDisabledFunding(),
            'id' => $paypalId,            
            'layout' => $block->getButtonLayout(), 
            'offerCredit' => false,
            'payeeEmail' => $block->getPayeeEmail(),
            'shape' => $block->getButtonShape(),
            'size' => $block->getButtonSize(),
        ]
    ]
];
if ($block->isCreditActive()) {
    $paypalCreditConfig = [
        'Gene_BraintreeHiConversion/js/paypal/button-cart' => [
            'config' => [
                'actionSuccess' => $block->getActionSuccess(),
                'clientToken' => $block->getClientToken(),
                'color' => 'darkblue',
                'displayName' => $block->getMerchantName(),
                'environment' => $block->getEnvironment(),
                'id' => $paypalCreditId,
                'layout' => $block->getButtonLayout(),
                'offerCredit' => true,
                'payeeEmail' => $block->getPayeeEmail(),
                'shape' => $block->getButtonShape(),
                'size' => $block->getButtonSize()
            ]
        ]
    ];
}
?>
<div data-mage-init="<?= $block->escapeHtmlAttr(json_encode($config)) ?>"
     class="paypal checkout paypal-logo braintree-paypal-btn braintree-paypal-logo <?= $block->escapeHtmlAttr($block->getContainerId()) ?>-container paypalCheckout <?= $block->escapeHtmlAttr($block->getExtraClassname()) ?>">
    <div data-currency="<?= $block->escapeHtmlAttr($block->getCurrency()) ?>"
         data-locale="<?= $block->escapeHtmlAttr($block->getLocale()) ?>"
         data-amount="<?= $block->escapeHtmlAttr($block->getAmount()) ?>"
         id="<?= $block->escapeHtmlAttr($paypalId) ?>"
         class="action-braintree-paypal-logo"></div>
</div>
<?php if ($block->isCreditActive()) : ?>
<div data-mage-init="<?= $block->escapeHtmlAttr(json_encode($paypalCreditConfig)) ?>"
     class="paypal checkout paypal-logo braintree-paypal-btn braintree-paypal-logo <?= $block->escapeHtmlAttr($block->getContainerId()) ?>-container paypalCredit <?= $block->escapeHtmlAttr($block->getExtraClassname()) ?>">
    <div data-currency="<?= $block->escapeHtmlAttr($block->getCurrency()) ?>"
         data-locale="<?= $block->escapeHtmlAttr($block->getLocale()) ?>"
         data-amount="<?= $block->escapeHtmlAttr($block->getAmount()) ?>"
         id="<?= $block->escapeHtmlAttr($paypalCreditId) ?>"
         class="action-braintree-paypal-logo"></div>
</div>
<?php endif; ?>