<?php
/**
 * @var \Magento\Braintree\Block\OneClickButton $block
 */
$paypalId = $block->getContainerId() . mt_rand();
$config = [
    'Magento_Braintree/js/paypal/product-page' => [
        'id' => $paypalId,
        'environment' => $block->getEnvironment(),
        'clientToken' => $block->getClientToken(),
        'displayName' => $block->getMerchantName(),
        'payeeEmail' => $block->getPayeeEmail(),
        'actionSuccess' => $block->getActionSuccess(),
        'offerCredit' => false,
        'fundingicons' => true,
        'shape' => $block->getButtonShape(),
        'size' => $block->getButtonSize(),
        'layout' => $block->getButtonLayout(),
        'color' => $block->getButtonColor(),
        'disabledFunding' => $block->getDisabledFunding()
    ]
];

$paypalCreditId = $block->getContainerId() . mt_rand();

if ($block->isCreditActive()) {
    $paypalCreditConfig = [
        'Magento_Braintree/js/paypal/product-page' => [
            'id' => $paypalCreditId,
            'environment' => $block->getEnvironment(),
            'clientToken' => $block->getClientToken(),
            'displayName' => $block->getMerchantName(),
            'payeeEmail' => $block->getPayeeEmail(),
            'actionSuccess' => $block->getActionSuccess(),
            'offerCredit' => true,
            'shape' => $block->getButtonShape(),
            'size' => $block->getButtonSize(),
            'layout' => $block->getButtonLayout(),
            'color' => 'darkblue',
        ]
    ];
}
?>

<div data-mage-init='<?= /** @noEscape */ json_encode($config) ?>'
     class="paypal checkout paypal-logo braintree-paypal-logo <?= $block->escapeHtmlAttr($block->getContainerId()) ?>-container">
    <div data-currency="<?= $block->escapeHtmlAttr($block->getCurrency()) ?>"
         data-locale="<?= $block->escapeHtmlAttr($block->getLocale()) ?>"
         data-amount="<?= $block->escapeHtmlAttr($block->getAmount()) ?>"
         id="<?= $block->escapeHtmlAttr($paypalId) ?>"
         class="action-braintree-paypal-logo"></div>
</div>

<?php if ($block->isCreditActive()) : ?>
<div data-mage-init='<?= /** @noEscape */ json_encode($paypalCreditConfig) ?>'
     class="paypal checkout paypal-logo braintree-paypal-logo <?= $block->escapeHtmlAttr($block->getContainerId()) ?>-container">
    <div data-currency="<?= $block->escapeHtmlAttr($block->getCurrency()) ?>"
         data-locale="<?= $block->escapeHtmlAttr($block->getLocale()) ?>"
         data-amount="<?= $block->escapeHtmlAttr($block->getAmount()) ?>"
         id="<?= $block->escapeHtmlAttr($paypalCreditId) ?>"
         class="action-braintree-paypal-logo"></div>
</div>
<?php endif; ?>